"""empty message

Revision ID: 4523c0c19f36
Revises: 
Create Date: 2023-04-30 10:53:13.720447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4523c0c19f36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency_from', sa.VARCHAR(length=32), nullable=False),
    sa.Column('currency_to', sa.VARCHAR(length=32), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
